"use client";
export default function Head() {
  return (
    <>
      <title>Abdias Ureña Soto</title>
      <meta content="width=device-width, initial-scale=1" name="viweport" />
      <meta name="description" content="Generated by create next app" />
    </>
  );
}
